config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tube.urls")),
    path('users', include("users.urls")),
    path('accounts/',include("allauth.urls")),# ←allauthのurls.pyを登録
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



tube/urls.py
from django.urls import path
from . import views


app_name = "tube"
urlpatterns =[
    path('', views.index, name="index"),

    path('search/', views.search, name="search"),

    # TIPS:<型:変数名>とすることでビューに変数を与えることができる
    #idをuuidにするので、intをuuidに変える。

    path('single/<uuid:video_pk>/', views.single, name="single"),
    path('single_mod/<uuid:video_pk>/', views.single_mod, name="single_mod"),
    path('news/', views.news, name="news"),
    path('news/<uuid:news_pk>/', views.news, name="news_single"),

    ##ランキングページ。DBからデータ抜き取って表示するだけ。GET文だけ
    path('rank/', views.rank, name="rank"),
    path('user_policy/', views.user_policy, name="user_policy"),

    # 以下認証済みユーザー専用
    path('video_comment_reply/<uuid:comment_pk>/', views.video_comment_reply, name="video_comment_reply"),
    path('video_comment_reply_to_reply/<uuid:videocommentreply_pk>/', views.video_comment_reply_to_reply,
         name="video_comment_reply_to_reply"),
    path('video_comment_edit/<uuid:comment_pk>/', views.video_comment_edit, name="video_comment_edit"),
    path('video_comment_reply_edit/<uuid:reply_pk>/', views.video_comment_reply_edit, name="video_comment_reply_edit"),
    path('video_comment_r_to_reply_edit/<uuid:r_to_reply_pk>/', views.video_comment_r_to_reply_edit,
         name="video_comment_r_to_reply_edit"),

    path('mypage/', views.mypage, name="mypage"),
    path('history/', views.history, name="history"),
    path('recommend/', views.recommend, name="recommend"),
    path('notify/', views.notify, name="notify"),
    path('mylist/', views.mylist, name="mylist"),
    path('upload/', views.upload, name="upload"),
    path('advertising_video/', views.advertising_video, name="advertising_video"),

    path('config/', views.config, name="config"),
    path('videoreport/<uuid:pk>/', views.videoreport, name="videoreport"),
    path('video_comment_report/<uuid:pk>/', views.video_comment_report, name="video_comment_report"),
    path('video_comment_reply_report/<uuid:pk>/', views.video_comment_reply_report, name="video_comment_reply_report"),
    path('video_comment_reply_to_reply_report/<uuid:pk>/', views.video_comment_reply_to_reply_report, name="video_comment_reply_to_reply_report"),

    path('usersingle/<uuid:pk>/', views.usersingle, name="usersingle"),
    path('userfollow/<uuid:pk>/', views.userfollow, name="userfollow"),
    path('userblock/<uuid:pk>/', views.userblock, name="userblock"),
    path('invite/<uuid:pk>/', views.invite, name="invite"),

    path('useredit/<uuid:pk>/', views.useredit, name="useredit"),

    #config.htmlコメント受け付け
    path('comment_accept/', views.comment_accept, name="comment_accept"),

    #個々の動画でコメント受付・拒否
    path('single_video_comment_accept/<uuid:video_pk>/', views.single_video_comment_accept, name="single_video_comment_accept"),
    path('single_video_comment_refuse/<uuid:video_pk>/', views.single_video_comment_refuse, name="single_video_comment_refuse"),

    #個々の動画のコメント承認制を解除する
    path('single_video_comment_approval1/<uuid:video_pk>/', views.single_video_comment_approval1, name="single_video_comment_approval1"),
    #個々の動画のコメントを承認制にする
    path('single_video_comment_approval2/<uuid:video_pk>/', views.single_video_comment_approval2, name="single_video_comment_approval2"),

    #全ての動画のコメント承認制を解除。
    path('comment_approval1/', views.comment_approval1, name="comment_approval1"),
    #全動画をコメント承認制にする。
    path('comment_approval2/', views.comment_approval2, name="comment_approval2"),

    #通知欄・動画コメント既読処理
    path('comment_already_read/', views.comment_already_read, name="comment_already_read"),
    path('comment_approval/', views.comment_approval, name="comment_approval"),

    #掲示板usersingle.html
    path('topic/<uuid:pk>/', views.topic, name="topic"),

    #広告動画
    path('advertising_videoreport/<uuid:pk>/', views.advertising_videoreport, name="advertising_videoreport"),
    path('advertising_video_single/<uuid:video_pk>/', views.advertising_video_single, name="advertising_video_single"),
    path('advertising_video_mod/<uuid:video_pk>/', views.advertising_video_mod, name="advertising_video_mod"),

]

tube/forms.py
from django import forms
from .models import Notify,NotifyTarget,News,UserPolicy,VideoCommentRefuse,VideoCommentApproval,Report,Topic,GoodAdvertisement,BadAdvertisement,AdvertisingVideo
from users.models import CustomUser



class NewsAdminForm(forms.ModelForm):

    class Meta:
        model   = News
        fields  = [ "dt","start_date","end_date","category","title","content" ]

    content     = forms.CharField(  widget  = forms.Textarea( attrs={ "maxlength":str(News.content.field.max_length), } ),
                                    label   = News.content.field.verbose_name
                                    )

class NotifyAdminForm(forms.ModelForm):

    class Meta:
        model   = Notify
        fields  = [ "category","dt","title","content", ]


    content     = forms.CharField(  widget  = forms.Textarea( attrs={ "maxlength":str(Notify.content.field.max_length), } ),
                                    label   = Notify.content.field.verbose_name
                                    )


class NotifyTargetAdminForm(forms.ModelForm):

    class Meta:
        model   = NotifyTarget
        fields  = [ "notify","user" ]

class UserPolicyForm(forms.ModelForm):

    class Meta:
        model   = UserPolicy
        fields  = [ "accept"]
        labels  = { "accept":"利用規約に同意する。"}

class CommentRefuseForm(forms.ModelForm):

    class Meta:
        model  = VideoCommentRefuse
        fields = ["video_comment_refuse"] #全ての動画に対するコメント拒否

class CommentApprovalForm(forms.ModelForm):

    class Meta:
        model  = VideoCommentApproval
        fields = ["video_comment_approval"] #全動画をコメント承認制に


class ReportForm(forms.ModelForm):

    class Meta:
        model  = Report
        fields = [ "report_user","reported_user","reason","category","target","target_id" ]


class UserInformationForm(forms.ModelForm):

    class Meta:
        model  = CustomUser
        fields =[ "handle_name","self_introduction"]


class TopicForm(forms.ModelForm):

    class Meta:
        model  = Topic
        fields = ["content"]



class GoodAdvertisementForm(forms.ModelForm):

    class Meta:
        model   = GoodAdvertisement
        fields  = [ "target","user",]


class BadAdvertisementForm(forms.ModelForm):

    class Meta:
        model   = BadAdvertisement
        fields  = [ "target","user",]


class AdvertisingVideoEditForm(forms.ModelForm):

    class Meta:
        model  = AdvertisingVideo
        fields =[ "title","description","category", ]

tube/views.py
from rest_framework import status,views,response

from django.shortcuts import render, redirect, HttpResponse

from django.http import HttpResponseForbidden #追加

from django.db.models.functions import TruncMonth
from django.db.models import Q,Count,Sum
from django.http.response import JsonResponse
from django.template.loader import render_to_string

from django.core.paginator import Paginator

from django.core.mail import send_mail

from django.conf import settings

from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone

from .models import (  Video,VideoCategory,VideoComment,VideoCommentReply,VideoCommentReplyToReply,
                    MyList,History,GoodVideo,NotifyTarget,Notify,News,NewsCategory,UserPolicy,Activity,
                    ReportCategory,VideoCommentRefuse,VideoCommentApproval,Topic,GoodTopic,AdvertisingVideo,
                    AdvertisingCategory,GoodAdvertisement,BadAdvertisement )

from users.models import CustomUser,FollowUser,BlockUser,PrivateUser

from .serializer import ( VideoSerializer,ViewSerializer,VideoEditSerializer,VideoCommentSerializer,
                          VideoCommentEditSerializer,VideoCommentReplyEditSerializer,
                          VideoCommentReplyToReplyEditSerializer,VideoCommentReplySerializer,
                          VideoCommentReplyToReplySerializer,MyListSerializer,HistorySerializer,RateSerializer,
                          GoodSerializer,IconSerializer,FollowUserSerializer,BlockUserSerializer,NotifyTargetSerializer,
                          PrivateUserSerializer,AdvertisingVideoSerializer,AdvertisingVideoViewSerializer,
                          YearMonthSerializer,UUIDListSerializer )

from .forms import ( UserPolicyForm,CommentRefuseForm,CommentApprovalForm,ReportForm,UserInformationForm,
                     TopicForm,GoodAdvertisementForm,BadAdvertisementForm,AdvertisingVideoEditForm)


#python-magicで受け取ったファイルのMIMEをチェックする。
#MIMEについては https://developer.mozilla.org/ja/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types を参照。

from PIL import Image
import qrcode, datetime,base64,magic
from io import BytesIO

ALLOWED_MIME   = ["video/mp4"]

# アップロードの上限
LIMIT_SIZE     = 8000 * 1000 * 1000
AD_LIMIT_SIZE     = 200 * 1000 * 1000

DEFAULT_VIDEO_AMOUNT = 100
DEFAULT_TOPIC_AMOUNT = 10000
DEFAULT_HISTORY_AMOUNT = 10
COMMENTS_AMOUNT_PAGE = 10
SEARCH_AMOUNT_PAGE  = 10



#トップページ
class IndexView(views.APIView):

    def get(self, request,*args, **kwargs):

        topics = Topic.objects.all().order_by("-dt")[:DEFAULT_TOPIC_AMOUNT]
        t_amount = topics.count()
        paginator = Paginator(topics, 10)

        if "page" in request.GET:
            topics = paginator.get_page(request.GET["page"])
        else:
            topics = paginator.get_page(1)

        advertisements = AdvertisingVideo.objects.all()
        categories = VideoCategory.objects.all()

        if request.user.is_authenticated:

            # フォローユーザーの動画
            follows = Video.objects.filter(user__followed=request.user.id).exclude(private=True).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            f_amount = follows.count()
            paginator = Paginator(follows, 10)

            if "page" in request.GET:
                follows = paginator.get_page(request.GET["page"])
            else:
                follows = paginator.get_page(1)

            # 新着順(ブロックしたユーザーは除外)
            latests = Video.objects.exclude(user__blocked=request.user.id).exclude(private=True).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            if "category" in request.GET:
                category = request.GET["category"]
                latests = Video.objects.filter(category__name=category).exclude(user__blocked=request.user.id).exclude(private=True).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            amount    = latests.count()
            paginator = Paginator(latests, 10)

            if "page" in request.GET:
                latests = paginator.get_page(request.GET["page"])
            else:
                latests = paginator.get_page(1)


            context = {"latests": latests,
                       "follows": follows,
                       "amount":amount,
                       "f_amount":f_amount,
                       "topics":topics,
                       "t_amount":t_amount,
                       "advertisements":advertisements,
                       "categories":categories,
                       }
            return render(request, "tube/index.html", context)

        else:
            follows = False

            # 新着順
            latests = Video.objects.exclude(private=True).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            if "category" in request.GET:
                category = request.GET["category"]
                latests = Video.objects.filter(category__name=category).exclude(private=True).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            amount    = latests.count()
            paginator = Paginator(latests, 10)

            if "page" in request.GET:
                latests = paginator.get_page(request.GET["page"])
            else:
                latests = paginator.get_page(1)


            context = {"latests": latests,
                       "follows": follows,
                       "amount": amount,
                       "topics":topics,
                       "t_amount":t_amount,
                       "advertisements":advertisements,
                       "categories": categories,
                       }

        return render(request, "tube/index.html", context)

index = IndexView.as_view()

#アップロードページ
class UploadView(LoginRequiredMixin,views.APIView):

    def get(self,request, *args, **kwargs):

        userpolicy = UserPolicy.objects.filter(user=request.user.id).first()

        categories = VideoCategory.objects.all()

        context = {"categories": categories,
                   "userpolicy":userpolicy,
                   }

        return render(request, "tube/upload.html", context)


    def post(self, request, *args, **kwargs):

        request.data["user"]    = request.user.id
        serializer              = VideoSerializer(data=request.data)
        #mime_type               = magic.from_buffer(request.FILES["movie"].read(1024), mime=True)

        #XXX:Cloudinaryでファイルをアップロードする時、このファイル参照が原因で動画ファイルのアップロードに失敗してしまう。
        #この問題は後日対策をブログにて。これではMIMEの参照、ファイルサイズの制限も実現できない。
        """
        if request.FILES["movie"].size >= LIMIT_SIZE:
            mb = str(LIMIT_SIZE / 1000000)

            json = {"error": True,
                    "message": "The maximum file size is " + mb + "MB"}

            return JsonResponse(json)

        if mime_type not in ALLOWED_MIME:
            mime = str(ALLOWED_MIME)
            json = {"error": True,
                    "message": "The file you can post is " + mime + "."}

            return JsonResponse(json)
        """

        if serializer.is_valid():
            serializer.save()
        else:
            json    = { "error":True,
                        "message":"入力内容に誤りがあります。" }
            return JsonResponse(json)

        json    = { "error":False,
                    "message":"アップロード完了しました。" }

        return JsonResponse(json)


upload = UploadView.as_view()


#広告動画アップロードページ
class AdvertisingVideoUploadView(LoginRequiredMixin,views.APIView):

    def get(self,request, *args, **kwargs):

        userpolicy = UserPolicy.objects.filter(user=request.user.id).first()

        categories = AdvertisingCategory.objects.all()

        context = {"categories": categories,
                   "userpolicy":userpolicy,
                   }

        return render(request, "tube/advertising_video_upload.html", context)


    def post(self, request, *args, **kwargs):

        request.data["user"]    = request.user.id
        serializer              = AdvertisingVideoSerializer(data=request.data)
        mime_type               = magic.from_buffer(request.FILES["movie"].read(1024), mime=True)

        if request.FILES["movie"].size >= AD_LIMIT_SIZE:
            mb = str(AD_LIMIT_SIZE / 1000000)

            json = {"error": True,
                    "message": "The maximum file size is " + mb + "MB"}

            return JsonResponse(json)

        if mime_type not in ALLOWED_MIME:
            mime = str(ALLOWED_MIME)
            json = {"error": True,
                    "message": "The file you can post is " + mime + "."}

            return JsonResponse(json)

        if serializer.is_valid():
            serializer.save()
        else:
            json    = { "error":True,
                        "message":"入力内容に誤りがあります。" }
            return JsonResponse(json)

        json    = { "error":False,
                    "message":"アップロード完了しました。" }

        return JsonResponse(json)


advertising_video = AdvertisingVideoUploadView.as_view()


#検索結果表示ページ
class SearchView(views.APIView):

    def get(self, request, *args, **kwargs):
        print(request.GET)
        query = Q()
        page = 1

        if "word" in request.GET:
            word = request.GET["word"]

            if word == "" or word.isspace():
                return redirect("tube:index")

            word_list  = word.replace("　", " ").split(" ")
            word_lists = [ w for w in word_list if w != "" ]

            for w in word_lists:
                query &= Q( Q(title__icontains=w) | Q(description__icontains=w) | Q(user__handle_name__icontains=w) )

        if "page" in request.GET:
            page = request.GET["page"]

        # TODO:ここでログインしていれば、ブロックユーザーを除外した検索をする。
        if request.user.is_authenticated:


templates/tube/single/advertisement.html
{% extends "tube/base.html" %}
{% load humanize %}
{% load static %}
{% load param_change %}

{% block site_title %}TubeIntegrity{% endblock %}


{% block extra_head %}
{{ block.super }}

<!--video.jsのCDNを読み込む-->
<link href="https://vjs.zencdn.net/7.11.4/video-js.css" rel="stylesheet" />
<script src="https://vjs.zencdn.net/7.11.4/video.min.js"></script>

<!--video.jsのカスタムスキンを指定-->
<link rel="stylesheet" href="{% static 'tube/css/videojs.css' %}">

<script src="{% static 'tube/js/single.js' %}"></script>
<script src="{% static 'tube/js/report.js' %}"></script>
<script src="{% static 'tube/js/f5forbid.js' %}"></script>

{% endblock %}



{% block page_title %}TubeIntegrity{% endblock %}

{% block main %}

         {% include "tube/search_form.html" %}

    <div class="single_video_area">
        <div class="single_video_content">
            <div class="single_video_content_inner">
                <video id="video-js" class="single_video video-js vjs-default-skin vjs-big-play-centered vjs-16-9">
                    <source src="{{ video.movie.url }}" type="video/mp4">
                </video>
            </div>
        </div>

        <div class="single_video_subcontent">
            <div class="single_video_subcontent_inner">

                <input id="subcontent_tab_1" class="subcontent_tab_radio" type="radio" name="subcontent_tab" checked>

                {% if request.user == video.user %}
                <input id="subcontent_tab_4" class="subcontent_tab_radio" type="radio" name="subcontent_tab">
                {% endif %}

                <div class="subcontent_tab_label_area">
                    <label for="subcontent_tab_1" class="subcontent_tab_label">説明</label>

                    {% if request.user == video.user %}
                    <label for="subcontent_tab_4" class="subcontent_tab_label">投稿者オプション</label>
                    {% endif %}
                </div>


                <div class="single_video_description">

                    <div class="s_video_sub_inner">
                        <div class="s_video_sub_inner_left">
                            {% if video.user.usericon %}
                            <a href="{% url 'tube:usersingle' video.user.id %}"><img class="video_usericon" src="{{ video.user.usericon.url }}" alt="icon"></a>
                            {% else %}
                            <a href="{% url 'tube:usersingle' video.user.id %}"><img class="video_usericon" src="{% static 'tube/img/non_usericon.png' %}" alt="{{ icon }}"></a>
                            {% endif %}
                        </div>

                        <div class="s_video_sub_inner_right">
                            <div class="video_title" id="report_target_{{ video.id }}">{{ video.title }}</div>
                            <a href="{% url 'tube:usersingle' video.user.id %}"><div>{{ video.user.handle_name }} </div></a>

                            <div class="video_value">
                                <span class="v_value_span"><i class="far fa-play-circle"></i>{{ video.views|intcomma }}</span>
                            </div>

                            <div class="word">{{ video.dt }}</div>

                        </div>
                    </div>

                    {# 投稿者のフォロー。認証済みかつ投稿者以外のユーザーにだけフォローボタンを表示させる。本人のものは表示させない#}

                    {% if request.user.is_authenticated and request.user.id != video.user.id %}
                    <div class="array">
                        <form id="follow_user_form_{{ video.user.id }}" class="usersingle_form" action="{% url 'tube:userfollow' video.user.id  %}" method="POST">
                            {% csrf_token %}
                            {% if request.user in video.user.followed.all %}
                            <button class="follow btn btn-primary follow_btn" type="button" value="{{ video.user.id }}">フォロー中</button>
                            {% else %}
                            <button class="follow btn btn-outline-primary follow_btn" type="button" value="{{ video.user.id }}">フォローする</button>
                            {% endif %}
                        </form>
                        <form id="block_user_form" class="usersingle_form" action="{% url 'tube:userblock' video.user.id  %}" method="POST">
                            {% csrf_token %}
                            {% if request.user in video.user.blocked.all %}
                            <button class="block btn btn-danger follow_btn" type="button">ブロック中</button>
                            {% else %}
                            <button class="block btn btn-outline-danger follow_btn" type="button">ブロックする</button>
                            {% endif %}
                        </form>
                    </div>
                    {% endif %}


                    <div id="rating_message" class="js_message"></div>
                    <div class="single_video_mod_area">
                        {# いいね、悪いね #}
                        <div id="single_video_rating_area" class="single_video_rating_area">
                            {% include "tube/single/advertisement_rate.html" %}
                        </div>
                    </div>

                    {# 通報ボタン #}
                    {% if request.user.is_authenticated %}
                    <input id="video_report_chk" class="video_report_chk" type="checkbox" name="video_report_chk">
                    <div class="video_report_chk_label_area">
                        <label for="video_report_chk" class="video_report_label"><i class="fas fa-bell single_video_rating_button video_report_bell"></i></label>
                    </div>
                    <div id="video_report_form_area" class="video_report_form_area">
                        <form id="report_form_{{ video.id }}" class="report_form" action="{% url 'tube:advertising_videoreport' request.user.id %}" method="POST">
                            {% csrf_token %}
                            <select class="select_form" name="category">
                                <option value="">通報理由を選択してください</option>
                                {% for category in report_categories %}
                                <option value="{{ category.id }}">{{ category.name }}</option>
                                {% empty %}
                                <option value="">カテゴリがありません。</option>
                                {% endfor %}
                            </select>
                            <textarea class="textarea_form" name="reason" placeholder="報告理由をお書きください（200文字）。" maxlength="200"></textarea>
                            <button  class="report_submit btn btn-outline-primary btn-sm" value="{{ video.id }}" type="button"><i class="far fa-paper-plane"></i></button>
                        </form>
                    </div>
                    {% endif %}

                    <div class="video_description_area mb-1">{{ video.description|linebreaksbr|urlize  }}</div>

                </div>


                {% if request.user == video.user %}
                <div class="single_video_uploader">
                    <div>

                        {% if video.user.usericon %}
                        <a href="{% url 'tube:usersingle' video.user.id %}"><img class="video_usericon" src="{{ video.user.usericon.url }}" alt="icon"></a>
                        {% else %}
                        <a href="{% url 'tube:usersingle' video.user.id %}"><img class="video_usericon" src="{% static 'tube/img/non_usericon.png' %}" alt="{{ icon }}"></a>
                        {% endif %}

                        <a href="{% url 'tube:usersingle' video.user.id %}"><div>{{ video.user.handle_name }}</div></a>


                        <input id="edit_tab_1" class="edit_tab_radio" type="radio" name="edit_tab" checked><label for="edit_tab_1" class="edit_tab_label">編集</label>
                        <input id="edit_tab_2" class="edit_tab_radio" type="radio" name="edit_tab"><label for="edit_tab_2" class="edit_tab_label">削除</label>

                            <div class="edit_form">
                                <h3>投稿欄編集</h3>
                                <p>カテゴリー/タイトル/概要欄の編集ができます。</p>

                                <form id="video_update_form" action="{% url 'tube:advertising_video_mod' video.id %}">
                                    {% csrf_token %}

                                    <select class="select_form" name="category">
                                        <option value="">カテゴリを選択してください</option>
                                        {% for category in categories %}
                                        <option value="{{ category.id }}" {% if category.id == video.category.id %}selected{% endif %}>{{ category.name }}</option>
                                        {% empty %}
                                        <option value="">カテゴリがありません。</option>
                                        {% endfor %}
                                    </select>

                                    <input class="input_form_text" type="text" value="{{ video.title }}" name="title" placeholder="タイトル...">
                                    <textarea class="textarea_form" name="description" rows="4" placeholder="概要欄...">{{ video.description }}</textarea>
                                    <input id="video_update" class="btn btn-outline-primary" type="button" value="編集">
                                </form>
                                <br class="my-2">

                            </div>

                            <div class="delete_form">

                                <!-- Ajax でDELETEメソッドを送信 -->
                                <form id="video_delete_form" action="{% url 'tube:advertising_video_mod' video.id %}" method="delete">
                                    {% csrf_token %}
                                    <h3>動画削除欄</h3>
                                    <p>この動画を削除しますか？</p>
                                    <input id="video_delete" class="btn btn-outline-danger" type="button" value="削除">
                                </form>
                            </div>

                            <div id="delete_message" class="js_message"></div>

                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

templates/tube/single/advertisement_rate.html
<form class="single_video_rating_content" action="{% url 'tube:advertising_video_mod' video.id %}">
    {% csrf_token %}
    <i class="far fa-thumbs-up single_video_rating_button rating_good {% if already_good %}already_good{% endif %}"></i>
    <span class="rating_num">{{ video.good.all|length }}</span>
</form>

<form class="single_video_rating_content" action="{% url 'tube:advertising_video_mod' video.id %}">
    {% csrf_token %}
    <i class="far fa-thumbs-down single_video_rating_button rating_bad {% if already_bad %}already_bad{% endif %}"></i>
    <span class="rating_num">{{ video.bad.all|length }}</span>
</form>

templates/tube/single/rate.html
<form class="single_video_rating_content" action="{% url 'tube:single_mod' video.id %}">
    {% csrf_token %}
    <i class="far fa-thumbs-up single_video_rating_button rating_good {% if already_good %}already_good{% endif %}"></i>
    <span class="rating_num">{{ video.good.all|length }}</span>
</form>

{% if video.private is not True %}
<form class="single_video_rating_content" action="{% url 'tube:single_mod' video.id %}">
    {% csrf_token %}
    <i class="far fa-list-alt single_video_rating_button mylist_entry {% if already_mylist %}already_mylist{% endif %}"></i>
    <span class="rating_num">{{ video.video_mylist.all|length }}</span>
</form>
{% endif %}