config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tube.urls")),
    path('users', include("users.urls")),
    path('accounts/',include("allauth.urls")),# ←allauthのurls.pyを登録
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



tube/urls.py
from django.urls import path
from . import views


app_name = "tube"
urlpatterns =[
    path('', views.index, name="index"),

    path('search/', views.search, name="search"),

    # TIPS:<型:変数名>とすることでビューに変数を与えることができる
    #idをuuidにするので、intをuuidに変える。

    path('single/<uuid:video_pk>/', views.single, name="single"),
    path('single_mod/<uuid:video_pk>/', views.single_mod, name="single_mod"),
    path('news/', views.news, name="news"),
    path('news/<uuid:news_pk>/', views.news, name="news_single"),

    ##ランキングページ。DBからデータ抜き取って表示するだけ。GET文だけ
    path('rank/', views.rank, name="rank"),
    path('user_policy/', views.user_policy, name="user_policy"),

    # 以下認証済みユーザー専用
    path('video_comment_reply/<uuid:comment_pk>/', views.video_comment_reply, name="video_comment_reply"),
    path('video_comment_reply_to_reply/<uuid:videocommentreply_pk>/', views.video_comment_reply_to_reply,
         name="video_comment_reply_to_reply"),
    path('video_comment_edit/<uuid:comment_pk>/', views.video_comment_edit, name="video_comment_edit"),
    path('video_comment_reply_edit/<uuid:reply_pk>/', views.video_comment_reply_edit, name="video_comment_reply_edit"),
    path('video_comment_r_to_reply_edit/<uuid:r_to_reply_pk>/', views.video_comment_r_to_reply_edit,
         name="video_comment_r_to_reply_edit"),

    path('mypage/', views.mypage, name="mypage"),
    path('history/', views.history, name="history"),
    path('recommend/', views.recommend, name="recommend"),
    path('notify/', views.notify, name="notify"),
    path('mylist/', views.mylist, name="mylist"),
    path('upload/', views.upload, name="upload"),
    path('advertising_video/', views.advertising_video, name="advertising_video"),

    path('config/', views.config, name="config"),
    path('videoreport/<uuid:pk>/', views.videoreport, name="videoreport"),
    path('video_comment_report/<uuid:pk>/', views.video_comment_report, name="video_comment_report"),
    path('video_comment_reply_report/<uuid:pk>/', views.video_comment_reply_report, name="video_comment_reply_report"),
    path('video_comment_reply_to_reply_report/<uuid:pk>/', views.video_comment_reply_to_reply_report, name="video_comment_reply_to_reply_report"),

    path('usersingle/<uuid:pk>/', views.usersingle, name="usersingle"),
    path('userfollow/<uuid:pk>/', views.userfollow, name="userfollow"),
    path('userblock/<uuid:pk>/', views.userblock, name="userblock"),
    path('invite/<uuid:pk>/', views.invite, name="invite"),

    path('useredit/<uuid:pk>/', views.useredit, name="useredit"),

    #config.htmlコメント受け付け
    path('comment_accept/', views.comment_accept, name="comment_accept"),

    #個々の動画でコメント受付・拒否
    path('single_video_comment_accept/<uuid:video_pk>/', views.single_video_comment_accept, name="single_video_comment_accept"),
    path('single_video_comment_refuse/<uuid:video_pk>/', views.single_video_comment_refuse, name="single_video_comment_refuse"),

    #個々の動画のコメント承認制を解除する
    path('single_video_comment_approval1/<uuid:video_pk>/', views.single_video_comment_approval1, name="single_video_comment_approval1"),
    #個々の動画のコメントを承認制にする
    path('single_video_comment_approval2/<uuid:video_pk>/', views.single_video_comment_approval2, name="single_video_comment_approval2"),

    #全ての動画のコメント承認制を解除。
    path('comment_approval1/', views.comment_approval1, name="comment_approval1"),
    #全動画をコメント承認制にする。
    path('comment_approval2/', views.comment_approval2, name="comment_approval2"),

    #通知欄・動画コメント既読処理
    path('comment_already_read/', views.comment_already_read, name="comment_already_read"),
    path('comment_approval/', views.comment_approval, name="comment_approval"),

    #掲示板usersingle.html
    path('topic/<uuid:pk>/', views.topic, name="topic"),

    #広告動画
    path('advertising_videoreport/<uuid:pk>/', views.advertising_videoreport, name="advertising_videoreport"),
    path('advertising_video_single/<uuid:video_pk>/', views.advertising_video_single, name="advertising_video_single"),
    path('advertising_video_mod/<uuid:video_pk>/', views.advertising_video_mod, name="advertising_video_mod"),

]

tube/forms.py
from django import forms
from .models import Notify,NotifyTarget,News,UserPolicy,VideoCommentRefuse,VideoCommentApproval,Report,Topic,GoodAdvertisement,BadAdvertisement,AdvertisingVideo
from users.models import CustomUser



class NewsAdminForm(forms.ModelForm):

    class Meta:
        model   = News
        fields  = [ "dt","start_date","end_date","category","title","content" ]

    content     = forms.CharField(  widget  = forms.Textarea( attrs={ "maxlength":str(News.content.field.max_length), } ),
                                    label   = News.content.field.verbose_name
                                    )

class NotifyAdminForm(forms.ModelForm):

    class Meta:
        model   = Notify
        fields  = [ "category","dt","title","content", ]


    content     = forms.CharField(  widget  = forms.Textarea( attrs={ "maxlength":str(Notify.content.field.max_length), } ),
                                    label   = Notify.content.field.verbose_name
                                    )


class NotifyTargetAdminForm(forms.ModelForm):

    class Meta:
        model   = NotifyTarget
        fields  = [ "notify","user" ]

class UserPolicyForm(forms.ModelForm):

    class Meta:
        model   = UserPolicy
        fields  = [ "accept"]
        labels  = { "accept":"利用規約に同意する。"}

class CommentRefuseForm(forms.ModelForm):

    class Meta:
        model  = VideoCommentRefuse
        fields = ["video_comment_refuse"] #全ての動画に対するコメント拒否

class CommentApprovalForm(forms.ModelForm):

    class Meta:
        model  = VideoCommentApproval
        fields = ["video_comment_approval"] #全動画をコメント承認制に


class ReportForm(forms.ModelForm):

    class Meta:
        model  = Report
        fields = [ "report_user","reported_user","reason","category","target","target_id" ]


class UserInformationForm(forms.ModelForm):

    class Meta:
        model  = CustomUser
        fields =[ "handle_name","self_introduction"]


class TopicForm(forms.ModelForm):

    class Meta:
        model  = Topic
        fields = ["content"]



class GoodAdvertisementForm(forms.ModelForm):

    class Meta:
        model   = GoodAdvertisement
        fields  = [ "target","user",]


class BadAdvertisementForm(forms.ModelForm):

    class Meta:
        model   = BadAdvertisement
        fields  = [ "target","user",]


class AdvertisingVideoEditForm(forms.ModelForm):

    class Meta:
        model  = AdvertisingVideo
        fields =[ "title","description","category", ]

tube/views.py
from rest_framework import status,views,response

from django.shortcuts import render, redirect, HttpResponse

from django.http import HttpResponseForbidden #追加

from django.db.models.functions import TruncMonth
from django.db.models import Q,Count,Sum
from django.http.response import JsonResponse
from django.template.loader import render_to_string

from django.core.paginator import Paginator

from django.core.mail import send_mail

from django.conf import settings

from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone

from .models import (  Video,VideoCategory,VideoComment,VideoCommentReply,VideoCommentReplyToReply,
                    MyList,History,GoodVideo,NotifyTarget,Notify,News,NewsCategory,UserPolicy,Activity,
                    ReportCategory,VideoCommentRefuse,VideoCommentApproval,Topic,GoodTopic,AdvertisingVideo,
                    AdvertisingCategory,GoodAdvertisement,BadAdvertisement )

from users.models import CustomUser,FollowUser,BlockUser,PrivateUser

from .serializer import ( VideoSerializer,ViewSerializer,VideoEditSerializer,VideoCommentSerializer,
                          VideoCommentEditSerializer,VideoCommentReplyEditSerializer,
                          VideoCommentReplyToReplyEditSerializer,VideoCommentReplySerializer,
                          VideoCommentReplyToReplySerializer,MyListSerializer,HistorySerializer,RateSerializer,
                          GoodSerializer,IconSerializer,FollowUserSerializer,BlockUserSerializer,NotifyTargetSerializer,
                          PrivateUserSerializer,AdvertisingVideoSerializer,AdvertisingVideoViewSerializer,
                          YearMonthSerializer,UUIDListSerializer )

from .forms import ( UserPolicyForm,CommentRefuseForm,CommentApprovalForm,ReportForm,UserInformationForm,
                     TopicForm,GoodAdvertisementForm,BadAdvertisementForm,AdvertisingVideoEditForm)


#python-magicで受け取ったファイルのMIMEをチェックする。
#MIMEについては https://developer.mozilla.org/ja/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types を参照。

from PIL import Image
import qrcode, datetime,base64,magic
from io import BytesIO

ALLOWED_MIME   = ["video/mp4"]

# アップロードの上限
LIMIT_SIZE     = 8000 * 1000 * 1000
AD_LIMIT_SIZE     = 200 * 1000 * 1000

DEFAULT_VIDEO_AMOUNT = 100
DEFAULT_TOPIC_AMOUNT = 10000
DEFAULT_HISTORY_AMOUNT = 10
COMMENTS_AMOUNT_PAGE = 10
SEARCH_AMOUNT_PAGE  = 10



#トップページ
class IndexView(views.APIView):

    def get(self, request,*args, **kwargs):

        topics = Topic.objects.all().order_by("-dt")[:DEFAULT_TOPIC_AMOUNT]
        t_amount = topics.count()
        paginator = Paginator(topics, 10)

        if "page" in request.GET:
            topics = paginator.get_page(request.GET["page"])
        else:
            topics = paginator.get_page(1)

        advertisements = AdvertisingVideo.objects.all()
        categories = VideoCategory.objects.all()

        if request.user.is_authenticated:

            # フォローユーザーの動画
            follows = Video.objects.filter(user__followed=request.user.id).exclude(private=True).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            f_amount = follows.count()
            paginator = Paginator(follows, 10)

            if "page" in request.GET:
                follows = paginator.get_page(request.GET["page"])
            else:
                follows = paginator.get_page(1)

            # 新着順(ブロックしたユーザーは除外)
            latests = Video.objects.exclude(user__blocked=request.user.id).exclude(private=True).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            if "category" in request.GET:
                category = request.GET["category"]
                latests = Video.objects.filter(category__name=category).exclude(user__blocked=request.user.id).exclude(private=True).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            amount    = latests.count()
            paginator = Paginator(latests, 10)

            if "page" in request.GET:
                latests = paginator.get_page(request.GET["page"])
            else:
                latests = paginator.get_page(1)


            context = {"latests": latests,
                       "follows": follows,
                       "amount":amount,
                       "f_amount":f_amount,
                       "topics":topics,
                       "t_amount":t_amount,
                       "advertisements":advertisements,
                       "categories":categories,
                       }
            return render(request, "tube/index.html", context)

        else:
            follows = False

            # 新着順
            latests = Video.objects.exclude(private=True).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            if "category" in request.GET:
                category = request.GET["category"]
                latests = Video.objects.filter(category__name=category).exclude(private=True).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            amount    = latests.count()
            paginator = Paginator(latests, 10)

            if "page" in request.GET:
                latests = paginator.get_page(request.GET["page"])
            else:
                latests = paginator.get_page(1)


            context = {"latests": latests,
                       "follows": follows,
                       "amount": amount,
                       "topics":topics,
                       "t_amount":t_amount,
                       "advertisements":advertisements,
                       "categories": categories,
                       }

        return render(request, "tube/index.html", context)

index = IndexView.as_view()

#アップロードページ
class UploadView(LoginRequiredMixin,views.APIView):

    def get(self,request, *args, **kwargs):

        userpolicy = UserPolicy.objects.filter(user=request.user.id).first()

        categories = VideoCategory.objects.all()

        context = {"categories": categories,
                   "userpolicy":userpolicy,
                   }

        return render(request, "tube/upload.html", context)


    def post(self, request, *args, **kwargs):

        request.data["user"]    = request.user.id
        serializer              = VideoSerializer(data=request.data)
        #mime_type               = magic.from_buffer(request.FILES["movie"].read(1024), mime=True)

        #XXX:Cloudinaryでファイルをアップロードする時、このファイル参照が原因で動画ファイルのアップロードに失敗してしまう。
        #この問題は後日対策をブログにて。これではMIMEの参照、ファイルサイズの制限も実現できない。
        """
        if request.FILES["movie"].size >= LIMIT_SIZE:
            mb = str(LIMIT_SIZE / 1000000)

            json = {"error": True,
                    "message": "The maximum file size is " + mb + "MB"}

            return JsonResponse(json)

        if mime_type not in ALLOWED_MIME:
            mime = str(ALLOWED_MIME)
            json = {"error": True,
                    "message": "The file you can post is " + mime + "."}

            return JsonResponse(json)
        """

        if serializer.is_valid():
            serializer.save()
        else:
            json    = { "error":True,
                        "message":"入力内容に誤りがあります。" }
            return JsonResponse(json)

        json    = { "error":False,
                    "message":"アップロード完了しました。" }

        return JsonResponse(json)


upload = UploadView.as_view()


#広告動画アップロードページ
class AdvertisingVideoUploadView(LoginRequiredMixin,views.APIView):

    def get(self,request, *args, **kwargs):

        userpolicy = UserPolicy.objects.filter(user=request.user.id).first()

        categories = AdvertisingCategory.objects.all()

        context = {"categories": categories,
                   "userpolicy":userpolicy,
                   }

        return render(request, "tube/advertising_video_upload.html", context)


    def post(self, request, *args, **kwargs):

        request.data["user"]    = request.user.id
        serializer              = AdvertisingVideoSerializer(data=request.data)
        mime_type               = magic.from_buffer(request.FILES["movie"].read(1024), mime=True)

        if request.FILES["movie"].size >= AD_LIMIT_SIZE:
            mb = str(AD_LIMIT_SIZE / 1000000)

            json = {"error": True,
                    "message": "The maximum file size is " + mb + "MB"}

            return JsonResponse(json)

        if mime_type not in ALLOWED_MIME:
            mime = str(ALLOWED_MIME)
            json = {"error": True,
                    "message": "The file you can post is " + mime + "."}

            return JsonResponse(json)

        if serializer.is_valid():
            serializer.save()
        else:
            json    = { "error":True,
                        "message":"入力内容に誤りがあります。" }
            return JsonResponse(json)

        json    = { "error":False,
                    "message":"アップロード完了しました。" }

        return JsonResponse(json)


advertising_video = AdvertisingVideoUploadView.as_view()


#検索結果表示ページ
class SearchView(views.APIView):

    def get(self, request, *args, **kwargs):
        print(request.GET)
        query = Q()
        page = 1

        if "word" in request.GET:
            word = request.GET["word"]

            if word == "" or word.isspace():
                return redirect("tube:index")

            word_list  = word.replace("　", " ").split(" ")
            word_lists = [ w for w in word_list if w != "" ]

            for w in word_lists:
                query &= Q( Q(title__icontains=w) | Q(description__icontains=w) | Q(user__handle_name__icontains=w) )

        if "page" in request.GET:
            page = request.GET["page"]

        # TODO:ここでログインしていれば、ブロックユーザーを除外した検索をする。
        if request.user.is_authenticated:


templates/tube/mypage/mypage.html
{% extends "tube/mypage_base.html" %}
{% load humanize %}
{% load static %}
{% load param_change %}


{% block extra_head %}
{{ block.super }}

<script src="{% static 'tube/js/usericon.js' %}"></script>

{% endblock %}

{% block mypage_content %}



    <h2 class="word_blue">基本情報</h2>

    <table>
        {% if custom_user.usericon %}
        <tr id="mypage_usericon_area">
            {% include "tube/mypage/mypage_usericon.html" %}
        </tr>
        {% endif %}
    </table>

    <table class="mypage_introduction_area">
        <tr>
            <td>ユーザー名</td>
            <td>{{ custom_user.username }}</td>
        </tr>
        <tr>
            <td>ハンドルネーム</td>
            <td>{{ custom_user.handle_name }}</td>
        </tr>
        <tr>
            <td>最終ログイン</td>
            <td>{{ custom_user.last_login }}</td>
        </tr>
        <tr>
            <td>メールアドレス</td>
            <td>{{ custom_user.email }}</td>
        </tr>
        <tr>
            <td>自己紹介</td>
            <td>{{ custom_user.self_introduction|linebreaksbr|urlize }}</td>
        </tr>
    </table></br>

    <input id="tab_system_radio_1" class="tab_system_radio" type="radio" name="tab_system_radio" checked>
    <input id="tab_system_radio_2" class="tab_system_radio" type="radio" name="tab_system_radio">
    <input id="tab_system_radio_3" class="tab_system_radio" type="radio" name="tab_system_radio">
    <input id="tab_system_radio_4" class="tab_system_radio" type="radio" name="tab_system_radio">

        <div class="tab_system_label_area">
            <label class="tab_system_label" for="tab_system_radio_1">投稿動画</label>
            <label class="tab_system_label" for="tab_system_radio_2">高く評価した動画</label>
            <label class="tab_system_label" for="tab_system_radio_3">アイコン登録/変更</label>
            <label class="tab_system_label" for="tab_system_radio_4">基本情報登録/変更</label>
        </div>
        <div id="tab_system_area_1" class="tab_system_area">

        {% if amount > 0 %}
        <ul><li>{{ amount }}件中、{{ videos|length }}件表示しています。</li></ul>
        {% endif %}

            <div class="video_content_list">
                {% for video in videos %}
                <div class="mypage_video_content">
                    <a class="video_content_link" href="{% url 'tube:single' video.id %}">
                        {% if video.thumbnail %}
                        <img class="mypage_thumbnail" src="{{ video.thumbnail.url }}" alt="{{ video.title }}">
                        {% else %}
                        <img class="mypage_thumbnail" src="{% static 'tube/img/no_image.jpg' %}" alt="{{ video.title }}">
                        {% endif %}
                    </a>

                    <div class="index_video_content_inner">
                        <div class="index_video_content_inner_left">
                            {% if video.user.usericon %}
                            <a href="{% url 'tube:usersingle' video.user.id %}"><img class="index_usericon" src="{{ video.user.usericon.url }}" alt="icon"></a>
                            {% else %}
                            <a href="{% url 'tube:usersingle' video.user.id %}"><img class="index_usericon" src="{% static 'tube/img/non_usericon.png' %}" alt="{{ icon }}"></a>
                            {% endif %}
                        </div>

                        <div class="index_video_content_inner_right">
                            <a href="{% url 'tube:single' video.id %}"><div class="video_title">{{ video.title|truncatechars_html:25 }}</div></a>
                            <a href="{% url 'tube:usersingle' video.user.id %}"><div>{{ video.user.handle_name }} </div></a>

                            <div class="video_value">
                                <span class="v_value_span"><i class="far fa-play-circle"></i>{{ video.views|intcomma }}</span>
                                <span class="v_value_span"><i class="far fa-comment"></i>{{ video.comment.all|length }}</span>
                                <span class="v_value_span"><i class="far fa-list-alt"></i>{{ video.video_mylist.all|length }}</span>
                            </div>
                            <div class="word">{{ video.dt }}</div>
                            <div class="word">{{ video.category }}</div>
                        </div>
                    </div>


                </div>
                {% empty %}
                <div class="mypage_video_content"><p>投稿した動画はありません。<a href="{% url 'tube:upload' %}">アップロード</a>から投稿できます。</p></div>
                {% endfor %}
            </div>
            {% generate_pagelink request "page" "1" videos.paginator.num_pages videos.number %}
        </div>

        <div id="tab_system_area_2" class="tab_system_area">

            {% if g_amount > 0 %}
            <ul><li>{{ g_amount }}件中、{{ good_videos|length }}件表示しています。</li></ul>
            {% endif %}

            <div class="video_content_list">
                {% for video in good_videos %}
                <div class="mypage_video_content">
                    <a class="video_content_link" href="{% url 'tube:single' video.target.id %}">
                        {% if video.target.thumbnail %}
                        <img class="mypage_thumbnail" src="{{ video.target.thumbnail.url }}" alt="{{ video.target.title }}">
                        {% else %}
                        <img class="mypage_thumbnail" src="{% static 'tube/img/no_image.jpg' %}" alt="{{ video.target.title }}">
                        {% endif %}
                    </a>

                    <div class="index_video_content_inner">
                        <div class="index_video_content_inner_left">
                            {% if video.target.user.usericon %}
                            <a href="{% url 'tube:usersingle' video.target.user.id %}"><img class="index_usericon" src="{{ video.target.user.usericon.url }}" alt="icon"></a>
                            {% else %}
                            <a href="{% url 'tube:usersingle' video.target.user.id %}"><img class="index_usericon" src="{% static 'tube/img/non_usericon.png' %}" alt="{{ icon }}"></a>
                            {% endif %}
                        </div>

                        <div class="index_video_content_inner_right">
                            <a href="{% url 'tube:single' video.target.id %}"><div class="video_title">{{ video.target.title|truncatechars_html:25 }}</div></a>
                            <a href="{% url 'tube:usersingle' video.target.user.id %}"><div>{{ video.target.user.handle_name }} </div></a>

                            <div class="video_value">
                                <span class="v_value_span"><i class="far fa-play-circle"></i>{{ video.target.views|intcomma }}</span>
                                <span class="v_value_span"><i class="far fa-comment"></i>{{ video.target.comment.all|length }}</span>
                                <span class="v_value_span"><i class="far fa-list-alt"></i>{{ video.target.video_mylist.all|length }}</span>
                            </div>
                            <div class="word">{{ video.target.dt }}</div>
                            <div class="word">{{ video.target.category }}</div>
                        </div>
                    </div>

                </div>
                {% empty %}
                <div>高く評価した動画はありません。</div>
                {% endfor %}
            </div>
            {% generate_pagelink request "page" "1" good_videos.paginator.num_pages good_videos.number %}
        </div>

        <div id="tab_system_area_3" class="tab_system_area">

            <div>
                <div class="user-icon-dnd-wrapper">
                    <input id="icon_upload1" type="file" name="usericon" accept=".jpg,.png">
                    <div id="drop_area">drag and drop<br>or<br>click here.</div>
                </div>

                <form id="icon_upload_form" name="icon_upload_form" method="POST" action="{% url 'tube:mypage' %}" enctype="multipart/form-data">
                {% csrf_token %}
                    <div class="icon_canvas">
                        <div id="icon_clear_button"><i class="far fa-times-circle"></i></div>
                        <input id='scal' class="scaling" type='range' value='' min='5' max='400'><br>
                        <canvas id='cvs' width='300' height='300'></canvas><br>
                        <input id="icon_upload2" class="btn-gradient-radius" type="button" value="送信">
                    </div>
                </form>
            </div>
            <div id="upload_message" class="upload_message"></div>

        </div>
        <div id="tab_system_area_4" class="tab_system_area">
            <form id="information_update_form" action="{% url 'tube:useredit' request.user.id %}"  method="POST">
                {% csrf_token %}
                <input class="input_form_text" type="text" value="{{ request.user.handle_name }}" name="handle_name" placeholder="ハンドルネーム">
                <textarea class="textarea_form" name="self_introduction" rows="4" placeholder="自己紹介">{{ request.user.self_introduction }} </textarea>
                <button class="v_c_submit_button btn btn-outline-primary" type="submit"><i class="far fa-paper-plane"></i></button>
            </form>
        </div>

{% endblock %}

templates/tube/mypage/mypage_usericon.html
<td><img class="mypage_usericon" src="{{ custom_user.usericon.url }}" alt="icon"></td>