config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tube.urls")),
    path('users', include("users.urls")),
    path('accounts/',include("allauth.urls")),# ←allauthのurls.pyを登録
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



tube/urls.py
from django.urls import path
from . import views


app_name = "tube"
urlpatterns =[
    path('', views.index, name="index"),

    path('search/', views.search, name="search"),

    # TIPS:<型:変数名>とすることでビューに変数を与えることができる
    #idをuuidにするので、intをuuidに変える。

    path('single/<uuid:video_pk>/', views.single, name="single"),
    path('single_mod/<uuid:video_pk>/', views.single_mod, name="single_mod"),
    path('news/', views.news, name="news"),
    path('news/<uuid:news_pk>/', views.news, name="news_single"),

    ##ランキングページ。DBからデータ抜き取って表示するだけ。GET文だけ
    path('rank/', views.rank, name="rank"),
    path('user_policy/', views.user_policy, name="user_policy"),

    # 以下認証済みユーザー専用
    path('video_comment_reply/<uuid:comment_pk>/', views.video_comment_reply, name="video_comment_reply"),
    path('video_comment_reply_to_reply/<uuid:videocommentreply_pk>/', views.video_comment_reply_to_reply,
         name="video_comment_reply_to_reply"),
    path('video_comment_edit/<uuid:comment_pk>/', views.video_comment_edit, name="video_comment_edit"),
    path('video_comment_reply_edit/<uuid:reply_pk>/', views.video_comment_reply_edit, name="video_comment_reply_edit"),
    path('video_comment_r_to_reply_edit/<uuid:r_to_reply_pk>/', views.video_comment_r_to_reply_edit,
         name="video_comment_r_to_reply_edit"),

    path('mypage/', views.mypage, name="mypage"),
    path('history/', views.history, name="history"),
    path('recommend/', views.recommend, name="recommend"),
    path('notify/', views.notify, name="notify"),
    path('mylist/', views.mylist, name="mylist"),
    path('upload/', views.upload, name="upload"),
    path('advertising_video/', views.advertising_video, name="advertising_video"),

    path('config/', views.config, name="config"),
    path('videoreport/<uuid:pk>/', views.videoreport, name="videoreport"),
    path('video_comment_report/<uuid:pk>/', views.video_comment_report, name="video_comment_report"),
    path('video_comment_reply_report/<uuid:pk>/', views.video_comment_reply_report, name="video_comment_reply_report"),
    path('video_comment_reply_to_reply_report/<uuid:pk>/', views.video_comment_reply_to_reply_report, name="video_comment_reply_to_reply_report"),

    path('usersingle/<uuid:pk>/', views.usersingle, name="usersingle"),
    path('userfollow/<uuid:pk>/', views.userfollow, name="userfollow"),
    path('userblock/<uuid:pk>/', views.userblock, name="userblock"),
    path('invite/<uuid:pk>/', views.invite, name="invite"),

    path('useredit/<uuid:pk>/', views.useredit, name="useredit"),

    #config.htmlコメント受け付け
    path('comment_accept/', views.comment_accept, name="comment_accept"),

    #個々の動画でコメント受付・拒否
    path('single_video_comment_accept/<uuid:video_pk>/', views.single_video_comment_accept, name="single_video_comment_accept"),
    path('single_video_comment_refuse/<uuid:video_pk>/', views.single_video_comment_refuse, name="single_video_comment_refuse"),

    #個々の動画のコメント承認制を解除する
    path('single_video_comment_approval1/<uuid:video_pk>/', views.single_video_comment_approval1, name="single_video_comment_approval1"),
    #個々の動画のコメントを承認制にする
    path('single_video_comment_approval2/<uuid:video_pk>/', views.single_video_comment_approval2, name="single_video_comment_approval2"),

    #全ての動画のコメント承認制を解除。
    path('comment_approval1/', views.comment_approval1, name="comment_approval1"),
    #全動画をコメント承認制にする。
    path('comment_approval2/', views.comment_approval2, name="comment_approval2"),

    #通知欄・動画コメント既読処理
    path('comment_already_read/', views.comment_already_read, name="comment_already_read"),
    path('comment_approval/', views.comment_approval, name="comment_approval"),

    #掲示板usersingle.html
    path('topic/<uuid:pk>/', views.topic, name="topic"),

    #広告動画
    path('advertising_videoreport/<uuid:pk>/', views.advertising_videoreport, name="advertising_videoreport"),
    path('advertising_video_single/<uuid:video_pk>/', views.advertising_video_single, name="advertising_video_single"),
    path('advertising_video_mod/<uuid:video_pk>/', views.advertising_video_mod, name="advertising_video_mod"),

]

tube/forms.py
from django import forms
from .models import Notify,NotifyTarget,News,UserPolicy,VideoCommentRefuse,VideoCommentApproval,Report,Topic,GoodAdvertisement,BadAdvertisement,AdvertisingVideo
from users.models import CustomUser



class NewsAdminForm(forms.ModelForm):

    class Meta:
        model   = News
        fields  = [ "dt","start_date","end_date","category","title","content" ]

    content     = forms.CharField(  widget  = forms.Textarea( attrs={ "maxlength":str(News.content.field.max_length), } ),
                                    label   = News.content.field.verbose_name
                                    )

class NotifyAdminForm(forms.ModelForm):

    class Meta:
        model   = Notify
        fields  = [ "category","dt","title","content", ]


    content     = forms.CharField(  widget  = forms.Textarea( attrs={ "maxlength":str(Notify.content.field.max_length), } ),
                                    label   = Notify.content.field.verbose_name
                                    )


class NotifyTargetAdminForm(forms.ModelForm):

    class Meta:
        model   = NotifyTarget
        fields  = [ "notify","user" ]

class UserPolicyForm(forms.ModelForm):

    class Meta:
        model   = UserPolicy
        fields  = [ "accept"]
        labels  = { "accept":"利用規約に同意する。"}

class CommentRefuseForm(forms.ModelForm):

    class Meta:
        model  = VideoCommentRefuse
        fields = ["video_comment_refuse"] #全ての動画に対するコメント拒否

class CommentApprovalForm(forms.ModelForm):

    class Meta:
        model  = VideoCommentApproval
        fields = ["video_comment_approval"] #全動画をコメント承認制に


class ReportForm(forms.ModelForm):

    class Meta:
        model  = Report
        fields = [ "report_user","reported_user","reason","category","target","target_id" ]


class UserInformationForm(forms.ModelForm):

    class Meta:
        model  = CustomUser
        fields =[ "handle_name","self_introduction"]


class TopicForm(forms.ModelForm):

    class Meta:
        model  = Topic
        fields = ["content"]



class GoodAdvertisementForm(forms.ModelForm):

    class Meta:
        model   = GoodAdvertisement
        fields  = [ "target","user",]


class BadAdvertisementForm(forms.ModelForm):

    class Meta:
        model   = BadAdvertisement
        fields  = [ "target","user",]


class AdvertisingVideoEditForm(forms.ModelForm):

    class Meta:
        model  = AdvertisingVideo
        fields =[ "title","description","category", ]

tube/views.py
from rest_framework import status,views,response

from django.shortcuts import render, redirect, HttpResponse

from django.http import HttpResponseForbidden #追加

from django.db.models.functions import TruncMonth
from django.db.models import Q,Count,Sum
from django.http.response import JsonResponse
from django.template.loader import render_to_string

from django.core.paginator import Paginator

from django.core.mail import send_mail

from django.conf import settings

from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone

from .models import (  Video,VideoCategory,VideoComment,VideoCommentReply,VideoCommentReplyToReply,
                    MyList,History,GoodVideo,NotifyTarget,Notify,News,NewsCategory,UserPolicy,Activity,
                    ReportCategory,VideoCommentRefuse,VideoCommentApproval,Topic,GoodTopic,AdvertisingVideo,
                    AdvertisingCategory,GoodAdvertisement,BadAdvertisement )

from users.models import CustomUser,FollowUser,BlockUser,PrivateUser

from .serializer import ( VideoSerializer,ViewSerializer,VideoEditSerializer,VideoCommentSerializer,
                          VideoCommentEditSerializer,VideoCommentReplyEditSerializer,
                          VideoCommentReplyToReplyEditSerializer,VideoCommentReplySerializer,
                          VideoCommentReplyToReplySerializer,MyListSerializer,HistorySerializer,RateSerializer,
                          GoodSerializer,IconSerializer,FollowUserSerializer,BlockUserSerializer,NotifyTargetSerializer,
                          PrivateUserSerializer,AdvertisingVideoSerializer,AdvertisingVideoViewSerializer,
                          YearMonthSerializer,UUIDListSerializer )

from .forms import ( UserPolicyForm,CommentRefuseForm,CommentApprovalForm,ReportForm,UserInformationForm,
                     TopicForm,GoodAdvertisementForm,BadAdvertisementForm,AdvertisingVideoEditForm)


#python-magicで受け取ったファイルのMIMEをチェックする。
#MIMEについては https://developer.mozilla.org/ja/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types を参照。

from PIL import Image
import qrcode, datetime,base64,magic
from io import BytesIO

ALLOWED_MIME   = ["video/mp4"]

# アップロードの上限
LIMIT_SIZE     = 8000 * 1000 * 1000
AD_LIMIT_SIZE     = 200 * 1000 * 1000

DEFAULT_VIDEO_AMOUNT = 100
DEFAULT_TOPIC_AMOUNT = 10000
DEFAULT_HISTORY_AMOUNT = 10
COMMENTS_AMOUNT_PAGE = 10
SEARCH_AMOUNT_PAGE  = 10



#トップページ
class IndexView(views.APIView):

    def get(self, request,*args, **kwargs):

        topics = Topic.objects.all().order_by("-dt")[:DEFAULT_TOPIC_AMOUNT]
        t_amount = topics.count()
        paginator = Paginator(topics, 10)

        if "page" in request.GET:
            topics = paginator.get_page(request.GET["page"])
        else:
            topics = paginator.get_page(1)

        advertisements = AdvertisingVideo.objects.all()
        categories = VideoCategory.objects.all()

        if request.user.is_authenticated:

            # フォローユーザーの動画
            follows = Video.objects.filter(user__followed=request.user.id).exclude(private=True).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            f_amount = follows.count()
            paginator = Paginator(follows, 10)

            if "page" in request.GET:
                follows = paginator.get_page(request.GET["page"])
            else:
                follows = paginator.get_page(1)

            # 新着順(ブロックしたユーザーは除外)
            latests = Video.objects.exclude(user__blocked=request.user.id).exclude(private=True).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            if "category" in request.GET:
                category = request.GET["category"]
                latests = Video.objects.filter(category__name=category).exclude(user__blocked=request.user.id).exclude(private=True).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            amount    = latests.count()
            paginator = Paginator(latests, 10)

            if "page" in request.GET:
                latests = paginator.get_page(request.GET["page"])
            else:
                latests = paginator.get_page(1)


            context = {"latests": latests,
                       "follows": follows,
                       "amount":amount,
                       "f_amount":f_amount,
                       "topics":topics,
                       "t_amount":t_amount,
                       "advertisements":advertisements,
                       "categories":categories,
                       }
            return render(request, "tube/index.html", context)

        else:
            follows = False

            # 新着順
            latests = Video.objects.exclude(private=True).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            if "category" in request.GET:
                category = request.GET["category"]
                latests = Video.objects.filter(category__name=category).exclude(private=True).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            amount    = latests.count()
            paginator = Paginator(latests, 10)

            if "page" in request.GET:
                latests = paginator.get_page(request.GET["page"])
            else:
                latests = paginator.get_page(1)


            context = {"latests": latests,
                       "follows": follows,
                       "amount": amount,
                       "topics":topics,
                       "t_amount":t_amount,
                       "advertisements":advertisements,
                       "categories": categories,
                       }

        return render(request, "tube/index.html", context)

index = IndexView.as_view()

#アップロードページ
class UploadView(LoginRequiredMixin,views.APIView):

    def get(self,request, *args, **kwargs):

        userpolicy = UserPolicy.objects.filter(user=request.user.id).first()

        categories = VideoCategory.objects.all()

        context = {"categories": categories,
                   "userpolicy":userpolicy,
                   }

        return render(request, "tube/upload.html", context)


    def post(self, request, *args, **kwargs):

        request.data["user"]    = request.user.id
        serializer              = VideoSerializer(data=request.data)
        #mime_type               = magic.from_buffer(request.FILES["movie"].read(1024), mime=True)

        #XXX:Cloudinaryでファイルをアップロードする時、このファイル参照が原因で動画ファイルのアップロードに失敗してしまう。
        #この問題は後日対策をブログにて。これではMIMEの参照、ファイルサイズの制限も実現できない。
        """
        if request.FILES["movie"].size >= LIMIT_SIZE:
            mb = str(LIMIT_SIZE / 1000000)

            json = {"error": True,
                    "message": "The maximum file size is " + mb + "MB"}

            return JsonResponse(json)

        if mime_type not in ALLOWED_MIME:
            mime = str(ALLOWED_MIME)
            json = {"error": True,
                    "message": "The file you can post is " + mime + "."}

            return JsonResponse(json)
        """

        if serializer.is_valid():
            serializer.save()
        else:
            json    = { "error":True,
                        "message":"入力内容に誤りがあります。" }
            return JsonResponse(json)

        json    = { "error":False,
                    "message":"アップロード完了しました。" }

        return JsonResponse(json)


upload = UploadView.as_view()


#広告動画アップロードページ
class AdvertisingVideoUploadView(LoginRequiredMixin,views.APIView):

    def get(self,request, *args, **kwargs):

        userpolicy = UserPolicy.objects.filter(user=request.user.id).first()

        categories = AdvertisingCategory.objects.all()

        context = {"categories": categories,
                   "userpolicy":userpolicy,
                   }

        return render(request, "tube/advertising_video_upload.html", context)


    def post(self, request, *args, **kwargs):

        request.data["user"]    = request.user.id
        serializer              = AdvertisingVideoSerializer(data=request.data)
        mime_type               = magic.from_buffer(request.FILES["movie"].read(1024), mime=True)

        if request.FILES["movie"].size >= AD_LIMIT_SIZE:
            mb = str(AD_LIMIT_SIZE / 1000000)

            json = {"error": True,
                    "message": "The maximum file size is " + mb + "MB"}

            return JsonResponse(json)

        if mime_type not in ALLOWED_MIME:
            mime = str(ALLOWED_MIME)
            json = {"error": True,
                    "message": "The file you can post is " + mime + "."}

            return JsonResponse(json)

        if serializer.is_valid():
            serializer.save()
        else:
            json    = { "error":True,
                        "message":"入力内容に誤りがあります。" }
            return JsonResponse(json)

        json    = { "error":False,
                    "message":"アップロード完了しました。" }

        return JsonResponse(json)


advertising_video = AdvertisingVideoUploadView.as_view()


#検索結果表示ページ
class SearchView(views.APIView):

    def get(self, request, *args, **kwargs):
        print(request.GET)
        query = Q()
        page = 1

        if "word" in request.GET:
            word = request.GET["word"]

            if word == "" or word.isspace():
                return redirect("tube:index")

            word_list  = word.replace("　", " ").split(" ")
            word_lists = [ w for w in word_list if w != "" ]

            for w in word_lists:
                query &= Q( Q(title__icontains=w) | Q(description__icontains=w) | Q(user__handle_name__icontains=w) )

        if "page" in request.GET:
            page = request.GET["page"]

        # TODO:ここでログインしていれば、ブロックユーザーを除外した検索をする。
        if request.user.is_authenticated:


templates/tube/advertising_video_upload.html
{% extends "tube/mypage_base.html" %}
{% load static %}

{% block extra_head %}
{{ block.super }}

<script src="{% static 'tube/js/thumbs.js' %}"></script>
<script src="{% static 'tube/js/upload.js' %}"></script>
{% endblock %}


{% block mypage_content %}

<h2>動画アップロード</h2>

{% if request.user.is_authenticated and request.user.id == userpolicy.user.id %}
<ul>
    <li>mp4ファイルのみ対応しています。</li>
    <li>ファイルサイズは上限200Mです。</li>
</ul>

        <div id="upload_message" class="upload_message"></div>

        <form id="video_upload_form" action="{% url 'tube:advertising_video' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <select class="select_form" name="category">
                <option value="">カテゴリを選択してください</option>
                {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
                {% empty %}
                <option value="">カテゴリがありません。</option>
                {% endfor %}
            </select>

            <input class = "input_form_text" placeholder="タイトル(50文字)..." name="title" maxlength="50">

            <textarea class="textarea_form" name="description" placeholder="動画説明文(500文字)..." rows="4" maxlength="500"></textarea>

            <div>動画(mp4)<input id="upload_form_video" type="file" accept="video/mp4" name="movie"></div>

            <!--TIPS:タブをdivで区切ると発動しなくなる、そこでbrタグを使って改行させる-->
            <br class="my-2">


            <input id="upload_tab_1" class="upload_tab_radio" type="radio" name="upload_tab" value="1" checked><label for="upload_tab_1" class="upload_tab_label">動画よりサムネイル指定</label>
            <input id="upload_tab_2" class="upload_tab_radio" type="radio" name="upload_tab" value="2"><label for="upload_tab_2" class="upload_tab_label">別途サムネイル指定</label>


            <div class="thumbnail_from_movie">
                <div class="thumbnail_create_area">
                    <div class="thumbnail_create_video"><video id="thumbnail_video" class="thumbnail_video" src="" controls muted></video></div>
                    <div class="thumbnail_create_button"><button id="thumbnail_button" class="thumbnail_button" type="button"><i class="far fa-images"></i>サムネイル指定</button></div>
                    <div class="thumbnail_create_canvas"><div class="thumbnail_create_canvas_explain">ここにサムネイルが表示される</div><canvas id="canvas"></canvas></div>
                </div>
            </div>


            <div class="another_thumbnail">
                <div>サムネイル(jpeg,png)：<input type="file" accept=".jpg,.png," name="thumbnail"></div>
            </div>

            <input id="upload" class="btn-gradient-radius" type="button" value="送信">
        </form>
{% else %}
<ul>
    <li>動画を投稿するには、利用規約への同意が必要です。</li>
    <a href="{% url 'tube:user_policy' %}"><div>利用規約</div></a>
</ul>
{% endif %}

{% endblock %}

templates/tube/base.html
{% extends "common/sidebar.html" %}
{% load static %}

{% block page_title %}{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'tube/css/style.css' %}">
<script src="{% static 'tube/js/script.js' %}"></script>

<script src="{% static 'common/js/ajax.js' %}"></script>
{% endblock %}

{% block header_title %}TubeIntegrity{% endblock %}

{% block header_right_content %}
    {% if request.user.is_authenticated %}

        <a class="header_icon" href="{% url 'tube:notify' %}" aria-label="notify">
            {% if request.user.notify_num %}
            <i class="fas fa-bell"></i>
            <span class="header_notify_num">{{ request.user.notify_num  }}</span>
            {% else %}
            <i class="far fa-bell"></i>
            {% endif %}
        </a>

        {% if request.user.usericon %}
        <a href="{% url 'tube:mypage' %}" aria-label="mypage">
            <img class="usericon" src="{{ request.user.usericon.url }}" alt="icon">
        </a>
        {% else %}
        <a class="header_icon" href="{% url 'tube:mypage' %}" aria-label="mypage">
            <i class="fas fa-user"></i>
        </a>
        {% endif %}

    {% else %}
        <a class="header_icon" href="{% url 'account_signup' %}" aria-label="signup">
            <i class="fas fa-user-plus"></i>
        </a>
        <a class="header_icon" href="{% url 'account_login' %}" aria-label="login">
            <i class="fas fa-sign-in-alt"></i>
        </a>
    {% endif %}
{% endblock %}

{% block sidebar_content %}
<div class="sidebar_content_area">

    <div class="sidebar_content">
        <a href="{% url 'tube:rank' %}" class="sidebar_icon"><i class="fas fa-crown"></i><div class="sidebar_explain">Ranking</div></a>
    </div>

    <div class="sidebar_content">
        <a href="{% url 'tube:search' %}" class="sidebar_icon"><i class="far fa-lightbulb"></i><div class="sidebar_explain">New Videos</div></a>
    </div>

    {% if request.user.is_authenticated %}
    {#  認証済みユーザーのアイコン #}
    <div class="sidebar_content">
        <a href="{% url 'tube:usersingle' request.user.id %}" class="sidebar_icon"><i class="fas fa-home"></i><div class="sidebar_explain">Home</div></a>
    </div>
    <div class="sidebar_content">
        <a href="{% url 'tube:mypage' %}" class="sidebar_icon"><i class="fas fa-user"></i><div class="sidebar_explain">MyPage</div></a>
    </div>
    <div class="sidebar_content">
        <a href="{% url 'tube:notify' %}" class="sidebar_icon"><i class="far fa-bell"></i><div class="sidebar_explain">Notice</div></a>
    </div>
    <div class="sidebar_content">
    <a href="{% url 'tube:history' %}" class="sidebar_icon"><i class="fas fa-history"></i><div class="sidebar_explain">History</div></a>
    </div>
    <div class="sidebar_content">
        <a href="{% url 'tube:mylist' %}" class="sidebar_icon"><i class="far fa-list-alt"></i><div class="sidebar_explain">MyList</div></a>
    </div>

    {% comment %}
    <div class="sidebar_content">
        <a href="{% url 'tube:recommend' %}" class="sidebar_icon"><i class="far fa-star"></i><div class="sidebar_explain">おすすめ</div></a>
    </div>
    {% endcomment %}

    <div class="sidebar_content">
        <a href="{% url 'tube:upload' %}" class="sidebar_icon"><i class="far fa-file-video"></i><div class="sidebar_explain">Upload</div></a>
    </div>
    <div class="sidebar_content">
        <a href="{% url 'tube:advertising_video' %}" class="sidebar_icon"><i class="fas fa-ad"></i><div class="sidebar_explain">Advertisement</div></a>
    </div>
    <div class="sidebar_content">
        <a href="{% url 'tube:config' %}" class="sidebar_icon"><i class="fas fa-cogs"></i><div class="sidebar_explain">Config</div></a>
    </div>
    <div class="sidebar_content">
        <a href="{% url 'account_logout' %}" class="sidebar_icon"><i class="fas fa-sign-out-alt"></i><div class="sidebar_explain">Logout</div></a>
    </div>
    {% else %}

    {# 未認証ユーザーのアイコン #}
    <div class="sidebar_content">
        <a href="{% url 'account_signup' %}" class="sidebar_icon"><i class="fas fa-user-plus"></i><div class="sidebar_explain">Sign-up</div></a>
    </div>
    <div class="sidebar_content">
        <a href="{% url 'account_login' %}" class="sidebar_icon"><i class="fas fa-sign-in-alt"></i><div class="sidebar_explain">Login</div></a>
    </div>
    {% endif %}

    {% comment %}
    <div class="sidebar_content">
        <a href="" class="sidebar_icon"><i class="far fa-question-circle"></i><div class="sidebar_explain">ヘルプ</div></a>
    </div>
    {% endcomment %}

    <div class="sidebar_content">
        <a href="{% url 'tube:user_policy' %}" class="sidebar_icon"><i class="fas fa-book"></i><div class="sidebar_explain">UserPolicy</div></a>
    </div>
    <div class="sidebar_content">
        <a href="{% url 'tube:news' %}" class="sidebar_icon"><i class="fas fa-info-circle"></i><div class="sidebar_explain">News</div></a>
    </div>
</div>
{% endblock %}

{% block main %}
{% endblock %}


templates/tube/config.html
{% extends "tube/mypage_base.html" %}
{% load static %}

{% block extra_head %}
{{ block.super }}
<script src="{% static 'tube/js/config.js' %}"></script>

{% endblock %}

{% block mypage_content %}

<h2>設定</h2>

        <form class="video_comment_refuse_form" method="POST" {% if refuse.video_comment_refuse %} action="{% url 'tube:comment_accept' %}" {% else %}action="{% url 'tube:config'%}"{% endif %}>
            {% csrf_token %}
            <input id="comment_refuse" class="comment_refuse_btn" type="checkbox" name="comment_refuse_btn" {% if refuse.video_comment_refuse %} checked {% endif %}>
            <label class="comment_refuse_label" for="comment_refuse"></label>

            {% if refuse.video_comment_refuse %}
                <div class="config_style">コメント拒否中。全動画のコメントを受け付ける。</div>
            {% else %}
                <div class="config_style">全動画のコメントを受け付けない。</div>
            {% endif %}
        </form>


        <form class="video_comment_approval_form" method="POST" {% if approval.video_comment_approval %} action="{% url 'tube:comment_approval1' %}" {% else %}action="{% url 'tube:comment_approval2'%}"{% endif %}>
            {% csrf_token %}
            <input id="comment_approval" class="comment_approval_btn" type="checkbox" {% if approval.video_comment_approval %} checked {% endif %}>
            <label class="comment_approval_label" for="comment_approval"></label>

            {% if approval.video_comment_approval %}
                <div class="config_style">全ての動画のコメント承認制を解除する。</div>
            {% else %}
                <div class="config_style">全ての動画のコメントを承認制にする。</div>
            {% endif %}
        </form>


{% endblock %}

templates/tube/mylist.html
{% extends "tube/mypage_base.html" %}
{% load static %}
{% load param_change %}

{% block extra_head %}
{{ block.super }}

<script src="{% static 'tube/js/mylist_delete.js' %}"></script>

{% endblock %}

{% block mypage_content %}

<h2 class="word_blue">マイリスト</h2>

{% if amount > 0 %}
<div>{{ amount }}件中、{{ mylists|length }}件表示しています。</div>

<div class="notify_control_area">
    <form name="mylist_clear_form" action="{% url 'tube:mylist' %}" method="POST">
        {% csrf_token %}
        <input class="notify_control_button"  type="submit" value="マイリストを空にする。">
    </form>
    <form id="mylist_clear_form" name="mylist_clear_form" action="{% url 'tube:mylist' %}" method="DELETE">
        {% csrf_token %}
        <button id="mylist_clear_btn" class="notify_control_button"  type="button">checkを削除</button>
    </form>
</div>
{% endif %}

{% for mylist in mylists %}
<input id="mylist_chk_{{ mylist.id }}" class="mylist_chk" type="checkbox" name="mylist_chk" value="{{ mylist.id }}">
<label class="mylist_chk_label" for="mylist_chk_{{ mylist.id }}">

<div class="video_list_view">

    <div class="video_list_thumbnail_area">
        {% if mylist.target.thumbnail %}
        <a class="video_list_thumbnail" href="{% url 'tube:single' mylist.target.id %}"><img src="{{ mylist.target.thumbnail.url }}" alt="thumbnail"></a>
        {% else %}
        <a class="video_list_thumbnail" href="{% url 'tube:single' mylist.target.id %}"><img src="{% static 'tube/img/no_image.jpg' %}" alt="thumbnail"></a>
        {% endif %}
            
    </div>
    <div class="video_list_description_area">
        <div class="video_list_description_inner">
            <h5 class="video_list_title"><a class="video_list_title_link" href="{% url 'tube:single' mylist.target.id %}">{{ mylist.target.title }}</a></h5>
            <div>{{ mylist.target.user.handle_name }}</div>
            <div class="video_list_description_overflow">{{ mylist.target.description }}</div>
            <div class="mb-2">登録日時:{{ mylist.dt }}</div>
        </div>
    </div>
</div>
</label>
{% empty %}
<p>マイリストはありません。</p>
{% endfor %}

{% generate_pagelink request "page" "1" mylists.paginator.num_pages mylists.number %}


{% endblock %}